"""add_admin_and_block

Revision ID: 46e93eaf1771
Revises: 1179593ac7bd
Create Date: 2023-04-01 13:58:50.803893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e93eaf1771'
down_revision = '1179593ac7bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_column('account', 'is_blocked')
    # ### end Alembic commands ###
